USE_LOCAL: false
BUCKET_NAME: datasets-reteai #tl-private-datasets
PROJECT_ID: splendid-flow-231921 #tl-private-dev-project
ROOT_DATASET_PATH: Cityscapes
MODEL_FORMAT: inference
MAX_BB_PER_IMAGE: 50

BACKGROUND_LABEL: 36
CLASSES: 35
OFFSET: 0
CONF_THRESH: 0.25
NMS_THRESH: 0.5
CM_IOU_THRESH: 0.25
OVERLAP_THRESH: 0.0625
SMALL_BBS_TH: 0.0003
STRIDES:
- 8
- 16
- 32
IMAGE_SIZE: [640, 640]
FEATURE_MAPS:
- - 80
  - 80
- - 40
  - 40
- - 20
  - 20
BOX_SIZES:
- - - 4.90625
    - 4.984375
  - - 2.34375
    - 19.03125
  - - 11.4765625
    - 12.9375
- - - 11.0625
    - 58.625
  - - 35.96875
    - 31.96875
  - - 152.625
    - 24.9375
- - - 120.6875
    - 105.9375
  - - 531
    - 59.59375
  - - 471.75
    - 237.125


